__title__ = 'XMindCopilot'
__description__ = 'XMind是基于Python实现，提供了对XMind思维导图进行创建、解析、更新的一站式解决方案！'
__keywords__ = 'xmind, mind mapping, 思维导图, XMind思维导图',
__url__ = 'https://github.com/zhuifengshen/xmind'
__author__ = 'MasterYip'
__author_email__ = '2205929492@qq.com'
__version__ = '0.0.1'
__license__ = 'MIT'
__cake__ = u'\u2728 \U0001f370 \u2728'
